#!/usr/bin/env python
import os
from bottle import route, default_app
import MySQLdb as mysql

def createDatabase():
    try:
        con= mysql.connect(user=os.environ["OPENSHIFT_MYSQL_DB_USERNAME"],
                            passwd=os.environ["OPENSHIFT_MYSQL_DB_PASSWORD"],
                            host=os.environ["OPENSHIFT_MYSQL_DB_HOST"],
                            port=int(os.environ["OPENSHIFT_MYSQL_DB_PORT"]))
    except BaseException as e:
        print(e)
    cur = con.cursor()
    try:
        cur.execute('CREATE DATABASE biba;')
    except BaseException as e:
        print(str(e))
        if "database exists" in str(e):
            print("DATABASE biba already present")
            pass
        else:
            raise e

createDatabase()
